version: '3.4'

services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - ${BACKEND_PORT}:3000

  frontend:
    build:
      context: ./frontend
      target: dev
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:5173"