version: '2.4'

services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./backend:/node/app
      - /node/app/node_modules

  frontend:
    build:
      context: ./frontend
      target: dev
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/node/app
      - /node/app/node_modules

volumes: 
  notused: