version: "3.4"

services:
  backend:
    volumes:
      - ./backend:/usr/src/app:rw
      - /usr/src/app/node_modules

  frontend:
    volumes:
      - ./frontend:/usr/src/app:rw
      - /usr/src/app/node_modules
